#!/bin/sh

# The script depends on the following packages, fonts and scripts:
#    - coreutils (for 'echo' command)
#    - grep (for 'grep' command)
#    - gawk (for 'awk' command)
#    - sed (for 'sed' command)
#    - acpi and acpid (for 'acpi' command)
#    - fontawesome (for symbols)

# Set default instance with parameter expansion
BLOCK_INSTANCE=${BLOCK_INSTANCE:-0}

state=$(acpi | grep "Battery $BLOCK_INSTANCE" -m 1 | awk '{print $3;}' | sed 's/,//')

charge=$(acpi | grep "Battery $BLOCK_INSTANCE" -m 1 | awk '{print $4;}' | sed 's/%,*//')

time=$(acpi | grep "Battery $BLOCK_INSTANCE" -m 1 | awk '$5 ~ /[0-9]+:[0-9]+:[0-9]+/ {print $5;}' | awk -F ':' '{print $1":"$2}')

if [ "$time" != "" ]
then
	time_string="($time)"
else
	time_string=""
fi

if [ "$state" == "Discharging" ]
then
	if [ $charge -lt 5 ]
	then
		echo " $charge% $time_string"
		echo ""
		echo "#ee829f"
                exit 33
	elif [ $charge -lt 15 ]
	then
		echo " $charge% $time_string"
		echo ""
		echo "#f5ef3d"
	elif [ $charge -lt 30 ]
	then
		echo " $charge% $time_string"
		echo ""
		echo
	elif [ $charge -lt 55 ]
	then
		echo " $charge% $time_string"
		echo ""
		echo
	elif [ $charge -lt 80 ]
	then
		echo " $charge% $time_string"
		echo ""
		echo
	else
		echo " $charge% $time_string"
		echo ""
		echo
	fi
else
	echo " $charge% $time_string"
	echo ""
	echo
fi
	
	
	
