#!/bin/sh

# The script depends on the following packages, fonts and scripts:
#    - coreutils (for 'wc' and 'echo' command)
#    - grep (for 'grep' command)
#    - gawk (for 'awk' command)
#    - bluez and bluez-utils (for 'bluetoothctl' command)
#    - fontawesome (for symbols)

# Set default instance with parameter expansion
BLOCK_INSTANCE=${BLOCK_INSTANCE:-""}

numOfControllers=$(echo "list" | bluetoothctl | awk '$1 == "Controller" {print $0;}' | wc -l) 

function printStatus {
	# Test if controller is powered
	if [ $(echo "show $1" | bluetoothctl | grep "Powered" -m 1 | awk '{print $2;}') == "yes" ]
	then
		echo " up"
		echo ""
	
		# Test if controller is discoverable
		if [ $(echo "show $1" | bluetoothctl | grep "Discoverable" -m 1 | awk '{print $2;}') == "yes" ]
		then
			echo "#2dd22d"
		else
			echo
		fi	
	else
		echo " down"
		echo ""
		echo
	fi
}

function printError {
	echo " No bluetooth"
	echo ""
	echo "#ee829f"
}


# If no controller is specified, test if more then 0 controllers (and by that a default controller) exist
if [ "$BLOCK_INSTANCE" == ""  ] && [ $numOfControllers -gt 0 ]
then
	printStatus ""

# If a controller is specified, test if the controller exists
elif [ $(echo "show $BLOCK_INSTANCE" | bluetoothctl | grep "not available" | wc -l) -eq 0 ]
then
	printStatus $BLOCK_INSTANCE

else
	printError
fi
