#!/bin/sh

# The script depends on the following packages, fonts and scripts:
#    - coreutils (for 'cut', 'nproc' and 'echo' command)
#    - bc (for 'bc' command)
#    - fontawesome (for symbols)

load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

echo " $load"
echo ""

if [ $(echo " $cpus <= $load" | bc) -eq 1 ]
then
	echo "#f5ef3d"
else
	echo
fi
