#!/bin/sh

## The script depends on the following packages, fonts and scripts:
#    - coreutils (for 'echo' command)
#    - grep (for 'grep' command)
#    - gawk (for 'awk' command)
#    - sed (for 'sed' command)
#    - bc (for 'bc' command)
#    - procps-ng (for 'free' command)
#    - fontawesome (for symbols)

 Set default instance with parameter expansion
BLOCK_INSTANCE=${BLOCK_INSTANCE:-Mem}

function printUsage {
	instance=$1

	totalKbs=$(free -k | grep "${instance}" -m 1 | awk '{print $2;}')
	usedKbs=$(free -k | grep "${instance}" -m 1 | awk '{print $3;}')

	printTotal=$(convertToPrintString $totalKbs)
	printUsed=$(convertToPrintString $usedKbs)

	echo " ${printUsed}/$printTotal"
	echo ""
	
	if [ $(echo "scale=1; ($usedKbs / $totalKbs) > 0.8" | bc) -eq 1 ]
	then
		echo "#f5ef3d"
	else
		echo
	fi

}

function convertToPrintString {
	valueKbs=$1

	if [ $valueKbs -lt 100 ]
	then
		echo "${value}kB";
	elif [ $(echo "scale=1; ($valueKbs / 1024) < 100" | bc) -eq 1 ]
	then
		echo "$(echo "scale=1; ($valueKbs / 1024)" | bc | sed 's/^\./0./')MB";
	else
		echo "$(echo "scale=1; ($valueKbs / 1024^2)" | bc | sed 's/^\./0./')GB";
	fi
}

printUsage $BLOCK_INSTANCE
