#!/bin/sh

## The script depends on the following packages, fonts and scripts:
#    - coreutils (for 'echo' command)
#    - grep (for 'grep' command)
#    - gawk (for 'awk' command)
#    - sed (for 'sed' command)
#    - alsa-utils (for 'amixer' command)
#    - fontawesome (for symbols)

 Set default instance with parameter expansion
BLOCK_INSTANCE=${BLOCK_INSTANCE:-Master}

vol=$(amixer get $BLOCK_INSTANCE |grep -m 1 % |awk '{print $5}'|sed 's/[^0-9]//g')

if [ "$(amixer get $BLOCK_INSTANCE |grep -m 1 % |awk '{print $6}')" == "[on]" ]
then
	state=on
else
	state=off
fi

if [ "$state" == "off" ]
then
	echo " muted"
	echo ""
	echo "#f5ef3d"
elif [ $vol -lt 50 ]
then
	echo " $vol%"
	echo ""
	echo
else
	echo " $vol%"
	echo ""
	echo	
fi
