#!/bin/sh

# The script depends on the following packages, fonts and scripts:
#    - rofi (for 'rofi' command)

G_COLOR=$1
TEXT_COLOR=$2
INACTIVE_BG_COLOR=$3
INACTIVE_TEXT_COLOR=$4
MONITOR_SIZE=$5
FONT_SIZE=$6 

# start the program launcher
rofi -show drun -lines 3 -eh 2 -width 100 -padding $MONITOR_SIZE -opacity "90" -bw 0 -color-enabled -color-window "$INACTIVE_BG_COLOR, $INACTIVE_BG_COLOR" -color-normal "$INACTIVE_BG_COLOR, $INACTIVE_TEXT_COLOR, $INACTIVE_BG_COLOR, $BG_COLOR, $TEXT_COLOR" -font "System San Francisco Display $FONT_SIZE"
