#!/bin/sh

# The script depends on the following packages, fonts and scripts:
#    - xf86-input-synaptics (for 'synclient' command)
#    - grep (for 'grep' and 'egrep' command)


if synclient -l | grep "TouchpadOff .*=.*0" ; then
    synclient TouchpadOff=1 ;
else
    synclient TouchpadOff=0 ;
fi
